apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf
  namespace: open5gs
  labels:
    app.kubernetes.io/component: upf
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: open5gs-upf
data:
  upf.yaml: |
    logger:
      level: info

    global:

    upf:
      pfcp:
        server:
        - dev: eth0
        client:
      gtpu:
        server:
        - dev: eth0
      session:
        - dev: ogstun
          dnn: internet
          subnet: 10.45.0.1/16
      metrics:
        server:
        - dev: eth0
          port: 9090
      info:
        - s_nssai:
            - sst: 1
              sd: "111111"
              dnn:
                - internet
