{
 "title": "5G Autoscaler Testbed",
 "description": "Dashboard pentru observabilitatea pod-urilor stub care simulează NF-uri 5G (AMF, SMF, UPF). Metrici expuse: load level, sesiuni active, CPU, memorie",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Load Levels per NF Stub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"nfstub_.*_load_level\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active 5G Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ues_active{namespace=\"nf-stubs\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "amf_session{namespace=\"nf-stubs\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_upffunction_upf_sessionnbr{namespace=\"nf-stubs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tub Pods CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(nfstub_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stub Pods Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nfstub_memory_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Count per NF Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count by (nf_type) (up{namespace=\"nf-stubs\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}